docker-compose/readme: fix support for home-assistant images >=2021.4.0 by mounting tmpfs for async_dns
```
2021-04-17 16:05:56 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2021-04-17 16:05:57 ERROR (MainThread) [homeassistant.setup] Setup failed for dhcp: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 192, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 11, in <module>
    from aiodiscover import DiscoverHosts
  File "/usr/local/lib/python3.8/site-packages/aiodiscover/__init__.py", line 11, in <module>
    from .discovery import DiscoverHosts  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/aiodiscover/discovery.py", line 5, in <module>
    from async_dns.core import REQUEST, DNSMessage, RandId, Record, types
  File "/usr/local/lib/python3.8/site-packages/async_dns/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.8/site-packages/async_dns/core/__init__.py", line 5, in <module>
    from .config import *
  File "/usr/local/lib/python3.8/site-packages/async_dns/core/config/__init__.py", line 2, in <module>
    from .root import *
  File "/usr/local/lib/python3.8/site-packages/async_dns/core/config/root.py", line 16, in <module>
    os.makedirs(CONFIG_DIR, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/hass/.config/async_dns'
2021-04-17 16:05:57 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of default_config. Setup failed for dependencies: dhcp
2021-04-17 16:05:57 ERROR (MainThread) [homeassistant.setup] Setup failed for default_config: Could not set up all dependencies.
```

workaround may be removed after home-assistant images upgraded to `async_dns>=1.1.10`:
https://github.com/gera2ld/async_dns/pull/23/files

related issue: https://github.com/home-assistant/core/issues/49205